services:
  device-tracker:
    container_name: device-tracker
    build: .
    volumes:
      - ${SCAN_PATH}:/app/scan.txt
      - ${LOG_PATH}:/app/log.txt
      - ${CONFIG_PATH}:/app/config.yml
    network_mode: host
    environment:
      DEVICE_TRACKER_CONFIG: /app/config.yml
